###Write TensorFlow code to provide the solutions to the following simple problems: 

In [1]:
import tensorflow as tf
import numpy as np

####1. Declare two constant tensors that have the values of 15 and 45. Add these two tensors and print out the results. 

In [2]:
m = tf.constant([15])
n = tf.constant([45])
k = tf.math.add(m,n)
print(k)

tf.Tensor([60], shape=(1,), dtype=int32)


#####2. Declare two variable tensors, a and b, that are initialized with scalar values of 2.75 and 8.5. Find their product and print out the result. 


In [3]:
a = tf.Variable([2.75])
b = tf.Variable([8.5])
f = tf.math.multiply(a,b)
print(f)

tf.Tensor([23.375], shape=(1,), dtype=float32)


#####3. Create two placeholders: x and y - that are both scalars of 32-bit floats. Assign 5.25 to x and 12.6 to y, multiply them together, and print out the results. 
 

In [9]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior() 
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
f = tf.math.multiply(x,y)
with tf.Session() as sess:
  print(sess.run([f], feed_dict = {x:[5.25] ,y:[12.6]}))


[array([66.15], dtype=float32)]


#####4. Create one placeholder: z - that is an N-Dimensional array (N can be >= 1) that can have any shape (shape = None). Feed this vector [1, 3, 5, 7, 9] into z and multiply it by 3. Display the results. 

In [17]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

z = tf.placeholder("float", None)
y = z * 3

with tf.Session() as session:
    result = session.run(y, feed_dict={z: [1, 3, 5, 7,9]})
    print(result)

[ 3.  9. 15. 21. 27.]


#####5. Create a constant tensor that is a matrix of the shape (8, 8). The matrix is initialized with all ones (1). Create a variable tensor that is also a matrix of the shape (8, 8) and initialized with random integer values between 0 and 99. Add these two tensors and display the results. 

In [32]:
sess = tf.Session()
mat_constant = sess.run(tf.constant(1,shape = (8,8)))
print(mat_constant,'\n')
mat_variable = sess.run(tf.random.uniform([8,8], minval =0, maxval=99, dtype = tf.int32))
print(mat_variable,'\n')
Result = sess.run(tf.add(mat_constant,mat_variable))
print(Result)
sess.close()

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]] 

[[12 98 46 30 86 70 38 48]
 [61 30 28 46 96 31 19 38]
 [47 95 96 72 62 31 59 73]
 [81 11 52 88 58 59 96 10]
 [69 47 34 25 28 96 97 65]
 [85 17 45 20 89 90 57  4]
 [12  6 85 27 35 47 48 25]
 [89 98 35 65  3 20 94 36]] 

[[13 99 47 31 87 71 39 49]
 [62 31 29 47 97 32 20 39]
 [48 96 97 73 63 32 60 74]
 [82 12 53 89 59 60 97 11]
 [70 48 35 26 29 97 98 66]
 [86 18 46 21 90 91 58  5]
 [13  7 86 28 36 48 49 26]
 [90 99 36 66  4 21 95 37]]
